name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_frontend:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.81.161.160
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd bms-devops/ && git pull
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server