name: Deploy to staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_frontend:
    name: Deploying everythign to the staging cluster

    steps:
      - name: SSH Into server
      - run: |
          echo ${{ SSH_PRIVATE_KEY}} &> ~/ssh_key
          ssh -i ~/ssh_key root@98.81.161.160
          cd bms-devops/ && git pull
          pnpm install
          pnpm run build
          pm2 restart fe-server
          pm2 restart http-server
          pm2 restart ws-server

