name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_frontend:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.81.161.160
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

            echo "Node Version:"
            node -v

            echo "NPM Version:"
            npm -v

            echo "PNPM Version:"
            pnpm -v

            echo "PM2 Version:"
            pm2 -v

            cd ~/bms-devops

            git pull origin main

            pnpm install

            pnpm run build

            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server

            pm2 save